name: Build, Test, and Run the Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install  # Corrected spacing issue

      - name: Build the application
        run: npm run build

      - name: Run tests
        run: npm test  

      - name: Run application (optional)
        run: npm start 
        # Note: Running the application in CI might not be necessary or may require additional setup.
